### PR TITLE
Remove tabs region from that which is checked

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by markconroy** [comment]
Hi @msayoung 

What's the reasoning behind ignoring the tabs region?

**Comment by msayoung** [comment]
Hi @markconroy - are you having fun? 

We're getting contrast errors, and the editors have no ability to update those tabs so I thought it would just confuse them.

**Comment by msayoung** [comment]
we should fix the contrast errors obviously :)

**Comment by markconroy** [comment]
Let's fix the contrast issues instead. So if anyone uses a custom theme and changes the CSS for their tabs, that will also get coverage.

And fully contrasting tabs will be good for localgov_base so everyone's a winner.

https://github.com/localgovdrupal/localgov_base/issues/282

**Pull request closed without merging**
